services:
  fastapi:
    build: fastapi/
    ports: 
      - 8502:8000
    networks:
      - deploy_network
      - postgresql_default
    container_name: streamcoinapi
    env_file:
      - .env

  streamlit:
    build: streamlit/
    ports: 
        - 8501:8501
    networks:
      - deploy_network
      - postgresql_default
    container_name: streamcoinapp
    env_file:
      - .env

networks:
  deploy_network:
    driver: bridge
  postgresql_default:
    external:
      name: postgresql_default